name: Build repo and deploy to pages

on:
 - workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install deno
      uses: denolib/setup-deno@v2
      with:
        deno-version: "1.17.1"
    
    - name: Build repo
      run: ./build.sh
      
    - name: Copy extra files
      run: cp README.md dist/README.md
      
    - name: Deploy to GH pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Show the README as a static page
          enable_jekyll: true
